export enum Colors {
  Primary = "#7B61FF",
  Secondary = "#917CFF",
  SystemDark = "#80858B",
  BackgroundBlack = "#000000",
  BackgroundDark = "#242426",
  BackgroundGraphite = "#323537",
  ErrorContext = "#FF5154",
  LightContext = "#AFB2B6",
  WhiteContext = "#FFFFFF",
  GreenTertiary = "#00A340",
  YellowTertiary = "#00A340",
  OrangeTertiary = "#F45D2D",
  TextColor = "var(--TextColor)",
  BackgroundTheme = "var(--BackgroundTheme)",
  InputBackground = "var(--InputBackground)",
  DetailMovieTitle = "var(--DetailMovieTitle)",
  DetailMovieText = "var(--DetailMovieColumnText)",
  DetailsRowNames = "var(--DetailsRowNames)",
}
